### ISSUE TITLE
Typhoeus::Response::Informations#return_message test error with curl 8.9.0

### ISSUE THREAD

**Issue by mtasaka** [typhoeus/typhoeus#723]
With curl 8.9.0, `Typhoeus::Response::Informations#return_message` test fails like:

```
Failures:

  1) Typhoeus::Response::Informations#return_message returns a message
     Failure/Error: expect(response.return_message).to eq("Couldn't connect to server")
     
       expected: #<Encoding:UTF-8> "Couldn't connect to server"
            got: #<Encoding:ASCII-8BIT> "Could not connect to server"
     
       (compared using ==)
     # /usr/share/gems/gems/rspec-support-3.13.1/lib/rspec/support.rb:110:in `block in <module:Support>'
     # /usr/share/gems/gems/rspec-support-3.13.1/lib/rspec/support.rb:119:in `notify_failure'
     # /usr/share/gems/gems/rspec-expectations-3.13.1/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /usr/share/gems/gems/rspec-expectations-3.13.1/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # /usr/share/gems/gems/rspec-expectations-3.13.1/lib/rspec/expectations/handler.rb:56:in `block in handle_matcher'
     # /usr/share/gems/gems/rspec-expectations-3.13.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /usr/share/gems/gems/rspec-expectations-3.13.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /usr/share/gems/gems/rspec-expectations-3.13.1/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # /usr/share/gems/gems/rspec-expectations-3.13.1/lib/rspec/expectations/expectation_target.rb:101:in `to'
     # ./spec/typhoeus/response/informations_spec.rb:27:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:263:in `instance_exec'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:263:in `block in run'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:486:in `block in run'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:486:in `run'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:259:in `run'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:642:in `map'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:642:in `run_examples'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:607:in `run'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:608:in `block in run'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:608:in `map'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:608:in `run'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:121:in `map'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/configuration.rb:2091:in `with_suite_hooks'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/reporter.rb:74:in `report'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:115:in `run_specs'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:89:in `run'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:71:in `run'
     # /usr/share/gems/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/share/gems/gems/rspec-core-3.13.0/exe/rspec:4:in `<top (required)>'
     # /usr/bin/rspec:25:in `load'
     # /usr/bin/rspec:25:in `<main>'
```
